#ifndef WCM_CONFIG_H
#define WCM_CONFIG_H

#define WCM_PROFILE_TINY 1u
#define WCM_PROFILE_STANDARD 2u
#define WCM_PROFILE_EXTENDED 3u

#ifndef WCM_PROFILE
#define WCM_PROFILE WCM_PROFILE_STANDARD
#endif

#if WCM_PROFILE == WCM_PROFILE_TINY
#define WCM_MAX_WITNESSES 24u
#define WCM_MAX_MODULES 8u
#define WCM_MAX_CAPABILITIES 8u
#define WCM_MAX_INGRESS 16u
#define WCM_MAX_INGRESS_PRODUCERS 2u
#define WCM_MAX_ACTUATORS 4u
#define WCM_MAX_SNAPSHOT_ITEMS 8u
#define WCM_MAX_EVENTS 8u
#define WCM_RUNTIME_STORAGE_BYTES 8192u
#elif WCM_PROFILE == WCM_PROFILE_EXTENDED
#define WCM_MAX_WITNESSES 128u
#define WCM_MAX_MODULES 32u
#define WCM_MAX_CAPABILITIES 32u
#define WCM_MAX_INGRESS 64u
#define WCM_MAX_INGRESS_PRODUCERS 8u
#define WCM_MAX_ACTUATORS 16u
#define WCM_MAX_SNAPSHOT_ITEMS 24u
#define WCM_MAX_EVENTS 64u
#define WCM_RUNTIME_STORAGE_BYTES 49152u
#else
#define WCM_MAX_WITNESSES 64u
#define WCM_MAX_MODULES 16u
#define WCM_MAX_CAPABILITIES 16u
#define WCM_MAX_INGRESS 32u
#define WCM_MAX_INGRESS_PRODUCERS 4u
#define WCM_MAX_ACTUATORS 8u
#define WCM_MAX_SNAPSHOT_ITEMS 16u
#define WCM_MAX_EVENTS 24u
#define WCM_RUNTIME_STORAGE_BYTES 20480u
#endif

#ifndef WCM_MAX_REBIND_REQS
#define WCM_MAX_REBIND_REQS 8u
#endif

#ifndef WCM_ANCHOR_PAYLOAD_SIZE
#define WCM_ANCHOR_PAYLOAD_SIZE 128u
#endif

#if WCM_MAX_CAPABILITIES > 64u
#error "WCM capability bitsets support at most 64 capabilities"
#endif
#if WCM_MAX_WITNESSES > 128u
#error "WCM supports at most 128 witness identifiers"
#endif

#endif
